spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;
    username: sa
    password:
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true

mybatis:
  type-aliases-package: com.example.practice.repository.domain #?? ??? ???? resultSet?? ????
  configuration:
    map-underscore-to-camel-case: true # ??? ???? ?? ?????? ??? ???
    default-fetch-size: 100 # select all ? ??? ??? ??? ?? ? ????
    default-statement-timeout: 30 # rdb? ??? ? timeout
  mapper-locations: classpath:mapper/*.xml # ??? ??
